# Generated by Django 3.2 on 2021-05-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='translate_text',
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate_track', to='track.track')),
            ],
        ),
    ]
