# Generated by Django 3.2 on 2021-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20210617_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, upload_to='tracks'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
