# Generated by Django 3.2 on 2021-05-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translate',
            new_name='Translation',
        ),
    ]
