# Generated by Django 3.2 on 2021-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_rename_translate_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
