# Generated by Django 3.2 on 2021-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
