# Generated by Django 3.2 on 2021-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_alter_translation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(),
        ),
    ]
