import random

from model_utils import Choices

LANG_CHOICES = Choices(
    ('af', 'afrikaans'),
    ('sq', 'albanian'),
    ('am', 'amharic'),
    ('ar', 'arabic'),
    ('hy', 'armenian'),
    ('az', 'azerbaijani'),
    ('eu', 'basque'),
    ('be', 'belarusian'),
    ('bn', 'bengali'),
    ('bs', 'bosnian'),
    ('bg', 'bulgarian'),
    ('ca', 'catalan'),
    ('ny', 'chichewa'),
    ('co', 'corsican'),
    ('hr', 'croatian'),
    ('cs', 'czech'),
    ('da', 'danish'),
    ('nl', 'dutch'),
    ('en', 'english'),
    ('eo', 'esperanto'),
    ('et', 'estonian'),
    ('tl', 'filipino'),
    ('fi', 'finnish'),
    ('fr', 'french'),
    ('fy', 'frisian'),
    ('gl', 'galician'),
    ('ka', 'georgian'),
    ('de', 'german'),
    ('el', 'greek'),
    ('gu', 'gujarati'),
    ('ht', 'haitian creole'),
    ('ha', 'hausa'),
    ('iw', 'hebrew'),
    ('he', 'hebrew'),
    ('hi', 'hindi'),
    ('hu', 'hungarian'),
    ('is', 'icelandic'),
    ('ig', 'igbo'),
    ('id', 'indonesian'),
    ('ga', 'irish'),
    ('it', 'italian'),
    ('ja', 'japanese'),
    ('jw', 'javanese'),
    ('kn', 'kannada'),
    ('kk', 'kazakh'),
    ('km', 'khmer'),
    ('ko', 'korean'),
    ('ku', 'kurdish (kurmanji)'),
    ('ky', 'kyrgyz'),
    ('lo', 'lao'),
    ('la', 'latin'),
    ('lv', 'latvian'),
    ('lt', 'lithuanian'),
    ('lb', 'luxembourgish'),
    ('mk', 'macedonian'),
    ('mg', 'malagasy'),
    ('ms', 'malay'),
    ('ml', 'malayalam'),
    ('mt', 'maltese'),
    ('mi', 'maori'),
    ('mr', 'marathi'),
    ('mn', 'mongolian'),
    ('my', 'myanmar (burmese)'),
    ('ne', 'nepali'),
    ('no', 'norwegian'),
    ('or', 'odia'),
    ('ps', 'pashto'),
    ('fa', 'persian'),
    ('pl', 'polish'),
    ('pt', 'portuguese'),
    ('pa', 'punjabi'),
    ('ro', 'romanian'),
    ('ru', 'russian'),
    ('sm', 'samoan'),
    ('gd', 'scots gaelic'),
    ('sr', 'serbian'),
    ('st', 'sesotho'),
    ('sn', 'shona'),
    ('sd', 'sindhi'),
    ('si', 'sinhala'),
    ('sk', 'slovak'),
    ('sl', 'slovenian'),
    ('so', 'somali'),
    ('es', 'spanish'),
    ('su', 'sundanese'),
    ('sw', 'swahili'),
    ('sv', 'swedish'),
    ('tg', 'tajik'),
    ('ta', 'tamil'),
    ('te', 'telugu'),
    ('th', 'thai'),
    ('tr', 'turkish'),
    ('tk', 'turkmen'),
    ('uk', 'ukrainian'),
    ('ur', 'urdu'),
    ('ug', 'uyghur'),
    ('uz', 'uzbek'),
    ('vi', 'vietnamese'),
    ('cy', 'welsh'),
    ('xh', 'xhosa'),
    ('yi', 'yiddish'),
    ('yo', 'yoruba'),
    ('zu', 'zulu'),
)

LocaleFaker = (
    ('bg', 'bulgarian'),
    ('cs', 'czech'),
    ('da', 'danish'),
    ('en', 'english'),
    ('fi', 'finnish'),
    ('fr', 'french'),
    ('de', 'german'),
    ('el', 'greek'),
    ('hi', 'hindi'),
    ('it', 'italian'),
    ('ja', 'japanese'),
    ('lv', 'latvian'),
    ('lt', 'lithuanian'),
    ('ru', 'russian'),
    ('sk', 'slovak'),
    ('sl', 'slovenian'),
    ('so', 'somali'),
    ('es', 'spanish'),
    ('sw', 'swahili'),
    ('sv', 'swedish'),
    ('uk', 'ukrainian'),

)

_rand_seed = 123


def get_random_lang_for_factory(new_value=True):
    global _rand_seed
    if new_value:
        _rand_seed = random.randint(0, 1_000)
    random.seed(_rand_seed)

    return LocaleFaker[random.randint(0, len(LocaleFaker))][0]

